version: 2

models:
  - name: stg_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values: ['pending', 'completed', 'shipped', 'cancelled']

  - name: stg_tickets
    columns:
      - name: ticket_id
        tests:
          - unique
          - not_null

  - name: dim_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null

  - name: fact_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      #This is a referential integrity test. It ensures that every user_id in fact_orders exists in dim_users
      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id